In [1]:
import pandas as pd 
import math
import numpy as np
import seaborn as sns
import pandas_profiling
from pandas_profiling import ProfileReport
from matplotlib import pyplot as plt
pd.options.display.max_rows = 10
pd.options.display.min_rows = 10

In [2]:
data = pd.read_csv('aac_shelter_outcomes.csv')
data.head(5)

,age_upon_outcome,animal_id,animal_type,breed,color,date_of_birth,datetime,monthyear,name,outcome_subtype,outcome_type,sex_upon_outcome
0,2 weeks,A684346,Cat,Domestic Shorthair Mix,Orange Tabby,2014-07-07T00:00:00,2014-07-22T16:04:00,2014-07-22T16:04:00,NaN,Partner,Transfer,Intact Male
1,1 year,A666430,Dog,Beagle Mix,White/Brown,2012-11-06T00:00:00,2013-11-07T11:47:00,2013-11-07T11:47:00,Lucy,Partner,Transfer,Spayed Female
2,1 year,A675708,Dog,Pit Bull,Blue/White,2013-03-31T00:00:00,2014-06-03T14:20:00,2014-06-03T14:20:00,*Johnny,NaN,Adoption,Neutered Male
3,9 years,A680386,Dog,Miniature Schnauzer Mix,White,2005-06-02T00:00:00,2014-06-15T15:50:00,2014-06-15T15:50:00,Monday,Partner,Transfer,Neutered Male
4,5 months,A683115,Other,Bat Mix,Brown,2014-01-07T00:00:00,2014-07-07T14:04:00,2014-07-07T14:04:00,NaN,Rabies Risk,Euthanasia,Unknown

In [3]:
data.describe()

,age_upon_outcome,animal_id,animal_type,breed,color,date_of_birth,datetime,monthyear,name,outcome_subtype,outcome_type,sex_upon_outcome
count,78248,78256,78256,78256,78256,78256,78256,78256,54370,35963,78244,78254
unique,46,70855,5,2128,525,5869,64361,64361,14574,19,9,5
top,1 year,A706536,Dog,Domestic Shorthair Mix,Black/White,2014-05-05T00:00:00,2016-04-18T00:00:00,2016-04-18T00:00:00,Bella,Partner,Adoption,Neutered Male
freq,14355,11,44242,23335,8153,112,39,39,344,19660,33112,27784

In [4]:
data[:100]

,age_upon_outcome,animal_id,animal_type,breed,color,date_of_birth,datetime,monthyear,name,outcome_subtype,outcome_type,sex_upon_outcome
0,2 weeks,A684346,Cat,Domestic Shorthair Mix,Orange Tabby,2014-07-07T00:00:00,2014-07-22T16:04:00,2014-07-22T16:04:00,NaN,Partner,Transfer,Intact Male
1,1 year,A666430,Dog,Beagle Mix,White/Brown,2012-11-06T00:00:00,2013-11-07T11:47:00,2013-11-07T11:47:00,Lucy,Partner,Transfer,Spayed Female
2,1 year,A675708,Dog,Pit Bull,Blue/White,2013-03-31T00:00:00,2014-06-03T14:20:00,2014-06-03T14:20:00,*Johnny,NaN,Adoption,Neutered Male
3,9 years,A680386,Dog,Miniature Schnauzer Mix,White,2005-06-02T00:00:00,2014-06-15T15:50:00,2014-06-15T15:50:00,Monday,Partner,Transfer,Neutered Male
4,5 months,A683115,Other,Bat Mix,Brown,2014-01-07T00:00:00,2014-07-07T14:04:00,2014-07-07T14:04:00,NaN,Rabies Risk,Euthanasia,Unknown
...,...,...,...,...,...,...,...,...,...,...,...,...
95,14 years,A562649,Dog,Border Collie Mix,White/Tricolor,2000-03-20T00:00:00,2014-03-20T18:37:00,2014-03-20T18:37:00,NaN,Suffering,Euthanasia,Spayed Female
96,2 years,A673137,Other,Rat,Black/White,2012-02-19T00:00:00,2014-02-20T14:49:00,2014-02-20T14:49:00,NaN,Partner,Transfer,Intact Female
97,1 year,A688904,Dog,German Shepherd Mix,Tan/White,2013-09-26T00:00:00,2014-12-04T17:22:00,2014-12-04T17:22:00,*Flicker,Partner,Transfer,Spayed Female
98,2 years,A686842,Dog,Staffordshire,Fawn/White,2012-08-27T00:00:00,2014-09-07T15:49:00,2014-09-07T15:49:00,*Herman,Aggressive,Euthanasia,Neutered Male
99,2 months,A691706,Cat,Domestic Longhair Mix,Brown Tabby,2014-10-01T00:00:00,2014-12-13T14:16:00,2014-12-13T14:16:00,Lucy,Foster,Adoption,Spayed Female

In [5]:
data[data['monthyear'] != data['datetime'] ]

Empty DataFrame
Columns: [age_upon_outcome, animal_id, animal_type, breed, color, date_of_birth, datetime, monthyear, name, outcome_subtype, outcome_type, sex_upon_outcome]
Index: []

In [6]:
data[data['date_of_birth'] != data['datetime'] ]

,age_upon_outcome,animal_id,animal_type,breed,color,date_of_birth,datetime,monthyear,name,outcome_subtype,outcome_type,sex_upon_outcome
0,2 weeks,A684346,Cat,Domestic Shorthair Mix,Orange Tabby,2014-07-07T00:00:00,2014-07-22T16:04:00,2014-07-22T16:04:00,NaN,Partner,Transfer,Intact Male
1,1 year,A666430,Dog,Beagle Mix,White/Brown,2012-11-06T00:00:00,2013-11-07T11:47:00,2013-11-07T11:47:00,Lucy,Partner,Transfer,Spayed Female
2,1 year,A675708,Dog,Pit Bull,Blue/White,2013-03-31T00:00:00,2014-06-03T14:20:00,2014-06-03T14:20:00,*Johnny,NaN,Adoption,Neutered Male
3,9 years,A680386,Dog,Miniature Schnauzer Mix,White,2005-06-02T00:00:00,2014-06-15T15:50:00,2014-06-15T15:50:00,Monday,Partner,Transfer,Neutered Male
4,5 months,A683115,Other,Bat Mix,Brown,2014-01-07T00:00:00,2014-07-07T14:04:00,2014-07-07T14:04:00,NaN,Rabies Risk,Euthanasia,Unknown
...,...,...,...,...,...,...,...,...,...,...,...,...
78251,1 month,A764894,Dog,Golden Retriever/Labrador Retriever,Brown/White,2017-12-04T00:00:00,2018-02-01T18:26:00,2018-02-01T18:26:00,NaN,Foster,Adoption,Spayed Female
78252,3 years,A764468,Dog,Mastiff Mix,Blue/White,2014-12-30T00:00:00,2018-02-01T18:06:00,2018-02-01T18:06:00,Max,NaN,Adoption,Neutered Male
78253,NaN,A766098,Other,Bat Mix,Brown,2017-02-01T00:00:00,2018-02-01T18:08:00,2018-02-01T18:08:00,NaN,Rabies Risk,Euthanasia,Unknown
78254,2 months,A765858,Dog,Standard Schnauzer,Red,2017-11-13T00:00:00,2018-02-01T18:32:00,2018-02-01T18:32:00,NaN,NaN,Adoption,Spayed Female
78255,2 months,A765857,Dog,Labrador Retriever Mix,White/Brown,2017-11-13T00:00:00,2018-02-01T18:44:00,2018-02-01T18:44:00,NaN,NaN,Adoption,Neutered Male

In [7]:
data = data.drop(['date_of_birth', 'monthyear'], axis=1)

In [8]:
data.head()

,age_upon_outcome,animal_id,animal_type,breed,color,datetime,name,outcome_subtype,outcome_type,sex_upon_outcome
0,2 weeks,A684346,Cat,Domestic Shorthair Mix,Orange Tabby,2014-07-22T16:04:00,NaN,Partner,Transfer,Intact Male
1,1 year,A666430,Dog,Beagle Mix,White/Brown,2013-11-07T11:47:00,Lucy,Partner,Transfer,Spayed Female
2,1 year,A675708,Dog,Pit Bull,Blue/White,2014-06-03T14:20:00,*Johnny,NaN,Adoption,Neutered Male
3,9 years,A680386,Dog,Miniature Schnauzer Mix,White,2014-06-15T15:50:00,Monday,Partner,Transfer,Neutered Male
4,5 months,A683115,Other,Bat Mix,Brown,2014-07-07T14:04:00,NaN,Rabies Risk,Euthanasia,Unknown

In [9]:
data.isna().sum()

age_upon_outcome        8
animal_id               0
animal_type             0
breed                   0
color                   0
datetime                0
name                23886
outcome_subtype     42293
outcome_type           12
sex_upon_outcome        2
dtype: int64

In [10]:
data[data['sex_upon_outcome'].isna()]

,age_upon_outcome,animal_id,animal_type,breed,color,datetime,name,outcome_subtype,outcome_type,sex_upon_outcome
16300,7 years,A667395,Dog,Dachshund,Brown Merle,2013-11-27T16:11:00,Diego,NaN,Return to Owner,NaN
68246,NaN,A737705,Dog,Labrador Retriever Mix,Black/White,2016-11-19T16:35:00,*Heddy,NaN,NaN,NaN

In [11]:
data.drop(data[data['sex_upon_outcome'].isna()].index, inplace = True)

In [12]:
data[data['sex_upon_outcome'].isna()]

Empty DataFrame
Columns: [age_upon_outcome, animal_id, animal_type, breed, color, datetime, name, outcome_subtype, outcome_type, sex_upon_outcome]
Index: []

In [13]:
data[data['outcome_type'].isna()]

,age_upon_outcome,animal_id,animal_type,breed,color,datetime,name,outcome_subtype,outcome_type,sex_upon_outcome
10753,1 year,A671017,Other,Fox Mix,Brown/Black,2014-01-20T08:27:00,NaN,NaN,NaN,Unknown
13270,0 years,A674209,Other,Bat Mix,Brown,2014-03-09T18:15:00,NaN,NaN,NaN,Unknown
13302,4 weeks,A679066,Other,Rabbit Sh,Brown,2014-05-16T00:00:00,NaN,NaN,NaN,Unknown
16951,1 year,A686025,Other,Bat Mix,Brown,2014-08-16T08:35:00,NaN,NaN,NaN,Unknown
29214,1 year,A744013,Other,Bat Mix,Black,2017-02-24T09:00:00,NaN,NaN,NaN,Unknown
...,...,...,...,...,...,...,...,...,...,...
69847,1 month,A755715,Cat,Domestic Shorthair Mix,Black Smoke,2017-08-21T10:09:00,*Louie,NaN,NaN,Intact Female
72037,1 month,A755716,Cat,Domestic Shorthair Mix,Blue,2017-08-21T10:09:00,*Huey,NaN,NaN,Intact Female
76709,10 years,A718046,Dog,Chihuahua Longhair Mix,Cream,2016-03-26T00:00:00,Bailey,NaN,NaN,Neutered Male
76710,10 months,A737930,Dog,Pit Bull Mix,Fawn/White,2016-11-17T10:59:00,King,NaN,NaN,Intact Male
76825,NaN,A764319,Dog,Pit Bull Mix,Black/White,2017-12-30T16:47:00,*Emma,NaN,NaN,Intact Female

In [14]:
data.drop(data[data['outcome_type'].isna()].index, inplace = True)

In [15]:
data[data['outcome_type'].isna()]

Empty DataFrame
Columns: [age_upon_outcome, animal_id, animal_type, breed, color, datetime, name, outcome_subtype, outcome_type, sex_upon_outcome]
Index: []

In [16]:
data[data['age_upon_outcome'].isna()]

,age_upon_outcome,animal_id,animal_type,breed,color,datetime,name,outcome_subtype,outcome_type,sex_upon_outcome
77976,NaN,A765547,Bird,Leghorn Mix,White/Red,2018-01-25T13:23:00,NaN,Partner,Transfer,Intact Female
78081,NaN,A765899,Dog,Miniature Poodle Mix,Black,2018-01-29T15:49:00,NaN,Suffering,Euthanasia,Neutered Male
78114,NaN,A765914,Cat,Domestic Shorthair Mix,Lynx Point,2018-01-29T18:08:00,NaN,Suffering,Euthanasia,Intact Male
78162,NaN,A765901,Dog,Maltese Mix,Buff,2018-01-31T08:14:00,NaN,Partner,Transfer,Intact Male
78208,NaN,A765960,Dog,Beagle/Catahoula,Tan/White,2018-02-01T09:21:00,NaN,Suffering,Euthanasia,Intact Male
78253,NaN,A766098,Other,Bat Mix,Brown,2018-02-01T18:08:00,NaN,Rabies Risk,Euthanasia,Unknown

In [17]:
data.drop(data[data['age_upon_outcome'].isna()].index, inplace = True)

In [18]:
data[data['age_upon_outcome'].isna()]

Empty DataFrame
Columns: [age_upon_outcome, animal_id, animal_type, breed, color, datetime, name, outcome_subtype, outcome_type, sex_upon_outcome]
Index: []

In [19]:
data.isna().sum()

age_upon_outcome        0
animal_id               0
animal_type             0
breed                   0
color                   0
datetime                0
name                23875
outcome_subtype     42280
outcome_type            0
sex_upon_outcome        0
dtype: int64

In [20]:
profile = ProfileReport(data)
profile

/Users/user/anaconda3/lib/python3.7/site-packages/pandas_profiling/describe.py:392: FutureWarning: The join_axes-keyword is deprecated. Use .reindex or .reindex_like on the result to achieve the same functionality.
  variable_stats = pd.concat(ldesc, join_axes=pd.Index([names]), axis=1)

имена почти все различные, много пропусков, полагаю имя не должно влиять на результат

In [21]:
data.drop(['name'], axis=1, inplace = True)

In [22]:
data.drop(['animal_id'], axis=1, inplace = True)

In [23]:
data

,age_upon_outcome,animal_type,breed,color,datetime,outcome_subtype,outcome_type,sex_upon_outcome
0,2 weeks,Cat,Domestic Shorthair Mix,Orange Tabby,2014-07-22T16:04:00,Partner,Transfer,Intact Male
1,1 year,Dog,Beagle Mix,White/Brown,2013-11-07T11:47:00,Partner,Transfer,Spayed Female
2,1 year,Dog,Pit Bull,Blue/White,2014-06-03T14:20:00,NaN,Adoption,Neutered Male
3,9 years,Dog,Miniature Schnauzer Mix,White,2014-06-15T15:50:00,Partner,Transfer,Neutered Male
4,5 months,Other,Bat Mix,Brown,2014-07-07T14:04:00,Rabies Risk,Euthanasia,Unknown
...,...,...,...,...,...,...,...,...
78250,1 month,Dog,Golden Retriever/Labrador Retriever,Brown/White,2018-02-01T18:40:00,Foster,Adoption,Neutered Male
78251,1 month,Dog,Golden Retriever/Labrador Retriever,Brown/White,2018-02-01T18:26:00,Foster,Adoption,Spayed Female
78252,3 years,Dog,Mastiff Mix,Blue/White,2018-02-01T18:06:00,NaN,Adoption,Neutered Male
78254,2 months,Dog,Standard Schnauzer,Red,2018-02-01T18:32:00,NaN,Adoption,Spayed Female
78255,2 months,Dog,Labrador Retriever Mix,White/Brown,2018-02-01T18:44:00,NaN,Adoption,Neutered Male

sex upon outcome разделить на пол и кастрированность
или лучше one code encoding
age_upon_outcomeпреобразовать к числу- возраст
datetime в datetime

In [24]:
import re
data1 = data
data1

,age_upon_outcome,animal_type,breed,color,datetime,outcome_subtype,outcome_type,sex_upon_outcome
0,2 weeks,Cat,Domestic Shorthair Mix,Orange Tabby,2014-07-22T16:04:00,Partner,Transfer,Intact Male
1,1 year,Dog,Beagle Mix,White/Brown,2013-11-07T11:47:00,Partner,Transfer,Spayed Female
2,1 year,Dog,Pit Bull,Blue/White,2014-06-03T14:20:00,NaN,Adoption,Neutered Male
3,9 years,Dog,Miniature Schnauzer Mix,White,2014-06-15T15:50:00,Partner,Transfer,Neutered Male
4,5 months,Other,Bat Mix,Brown,2014-07-07T14:04:00,Rabies Risk,Euthanasia,Unknown
...,...,...,...,...,...,...,...,...
78250,1 month,Dog,Golden Retriever/Labrador Retriever,Brown/White,2018-02-01T18:40:00,Foster,Adoption,Neutered Male
78251,1 month,Dog,Golden Retriever/Labrador Retriever,Brown/White,2018-02-01T18:26:00,Foster,Adoption,Spayed Female
78252,3 years,Dog,Mastiff Mix,Blue/White,2018-02-01T18:06:00,NaN,Adoption,Neutered Male
78254,2 months,Dog,Standard Schnauzer,Red,2018-02-01T18:32:00,NaN,Adoption,Spayed Female
78255,2 months,Dog,Labrador Retriever Mix,White/Brown,2018-02-01T18:44:00,NaN,Adoption,Neutered Male

In [25]:
data[data['sex_upon_outcome'].isna()]

Empty DataFrame
Columns: [age_upon_outcome, animal_type, breed, color, datetime, outcome_subtype, outcome_type, sex_upon_outcome]
Index: []

In [26]:
tmp = pd.DataFrame()

tmp['is_week'] = list(map(int, [re.match('.*week.*',i) != None for i in data['age_upon_outcome']]))

tmp['is_month'] = list(map(int, [re.match('.*month.*',i) != None for i in data['age_upon_outcome']]))

tmp['is_year'] = list(map(int, [re.match('.*year.*',i) != None for i in data['age_upon_outcome']]))

tmp['nub_age'] = list(map(int, [re.findall('[0-9]+',i)[0] for i in data['age_upon_outcome']]))

tmp['age'] = (tmp['is_week'] * 7 + tmp['is_month'] * 30 + tmp['is_year'] * 365) * tmp['nub_age']

tmp.index = data.index
tmp

       is_week  is_month  is_year  nub_age   age
0            1         0        0        2    14
1            0         0        1        1   365
2            0         0        1        1   365
3            0         0        1        9  3285
4            0         1        0        5   150
...        ...       ...      ...      ...   ...
78250        0         1        0        1    30
78251        0         1        0        1    30
78252        0         0        1        3  1095
78254        0         1        0        2    60
78255        0         1        0        2    60

[78237 rows x 5 columns]

In [27]:
data['age_days'] = tmp['age']
data.drop('age_upon_outcome', axis= 1,inplace = True)
data

,animal_type,breed,color,datetime,outcome_subtype,outcome_type,sex_upon_outcome,age_days
0,Cat,Domestic Shorthair Mix,Orange Tabby,2014-07-22T16:04:00,Partner,Transfer,Intact Male,14
1,Dog,Beagle Mix,White/Brown,2013-11-07T11:47:00,Partner,Transfer,Spayed Female,365
2,Dog,Pit Bull,Blue/White,2014-06-03T14:20:00,NaN,Adoption,Neutered Male,365
3,Dog,Miniature Schnauzer Mix,White,2014-06-15T15:50:00,Partner,Transfer,Neutered Male,3285
4,Other,Bat Mix,Brown,2014-07-07T14:04:00,Rabies Risk,Euthanasia,Unknown,150
...,...,...,...,...,...,...,...,...
78250,Dog,Golden Retriever/Labrador Retriever,Brown/White,2018-02-01T18:40:00,Foster,Adoption,Neutered Male,30
78251,Dog,Golden Retriever/Labrador Retriever,Brown/White,2018-02-01T18:26:00,Foster,Adoption,Spayed Female,30
78252,Dog,Mastiff Mix,Blue/White,2018-02-01T18:06:00,NaN,Adoption,Neutered Male,1095
78254,Dog,Standard Schnauzer,Red,2018-02-01T18:32:00,NaN,Adoption,Spayed Female,60
78255,Dog,Labrador Retriever Mix,White/Brown,2018-02-01T18:44:00,NaN,Adoption,Neutered Male,60

In [28]:
from sklearn import preprocessing
animal_type = data['animal_type'].get_values().reshape(-1, 1)

# One-hot encoding
oh_encoder = preprocessing.OneHotEncoder()
oh_encoder.fit(animal_type)
oh_result = oh_encoder.transform(animal_type).toarray()

/Users/user/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:2: FutureWarning: The 'get_values' method is deprecated and will be removed in a future version. Use '.to_numpy()' or '.array' instead.

In [29]:
name = ['Bird','Cat', 'Dog','Livestock','Other' ]

In [30]:
tmp = pd.DataFrame(oh_result, columns=name)
tmp.index = data.index

In [31]:
data = pd.concat([data, tmp], axis=1)
data.drop(['animal_type'], axis=1, inplace = True)

In [32]:
data

,breed,color,datetime,outcome_subtype,outcome_type,sex_upon_outcome,age_days,Bird,Cat,Dog,Livestock,Other
0,Domestic Shorthair Mix,Orange Tabby,2014-07-22T16:04:00,Partner,Transfer,Intact Male,14,0.0,1.0,0.0,0.0,0.0
1,Beagle Mix,White/Brown,2013-11-07T11:47:00,Partner,Transfer,Spayed Female,365,0.0,0.0,1.0,0.0,0.0
2,Pit Bull,Blue/White,2014-06-03T14:20:00,NaN,Adoption,Neutered Male,365,0.0,0.0,1.0,0.0,0.0
3,Miniature Schnauzer Mix,White,2014-06-15T15:50:00,Partner,Transfer,Neutered Male,3285,0.0,0.0,1.0,0.0,0.0
4,Bat Mix,Brown,2014-07-07T14:04:00,Rabies Risk,Euthanasia,Unknown,150,0.0,0.0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...
78250,Golden Retriever/Labrador Retriever,Brown/White,2018-02-01T18:40:00,Foster,Adoption,Neutered Male,30,0.0,0.0,1.0,0.0,0.0
78251,Golden Retriever/Labrador Retriever,Brown/White,2018-02-01T18:26:00,Foster,Adoption,Spayed Female,30,0.0,0.0,1.0,0.0,0.0
78252,Mastiff Mix,Blue/White,2018-02-01T18:06:00,NaN,Adoption,Neutered Male,1095,0.0,0.0,1.0,0.0,0.0
78254,Standard Schnauzer,Red,2018-02-01T18:32:00,NaN,Adoption,Spayed Female,60,0.0,0.0,1.0,0.0,0.0
78255,Labrador Retriever Mix,White/Brown,2018-02-01T18:44:00,NaN,Adoption,Neutered Male,60,0.0,0.0,1.0,0.0,0.0

In [33]:
data['Other'] += data['Bird']
data[data['Bird'] == 1]

,breed,color,datetime,outcome_subtype,outcome_type,sex_upon_outcome,age_days,Bird,Cat,Dog,Livestock,Other
1294,Chicken,Brown/Yellow,2014-07-16T13:03:00,Partner,Transfer,Intact Female,60,1.0,0.0,0.0,0.0,1.0
1347,Parakeet Mix,Green,2013-11-10T16:36:00,Partner,Transfer,Intact Male,365,1.0,0.0,0.0,0.0,1.0
1563,Bantam Mix,White,2014-04-29T11:29:00,NaN,Adoption,Intact Male,730,1.0,0.0,0.0,0.0,1.0
1617,Duck,Yellow/Black,2014-06-10T00:00:00,Partner,Transfer,Unknown,14,1.0,0.0,0.0,0.0,1.0
1655,Lark Mix,Brown/Black,2014-03-15T17:54:00,Suffering,Euthanasia,Unknown,365,1.0,0.0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...
76430,Chicken Mix,Red,2017-06-10T10:42:00,Offsite,Adoption,Unknown,180,1.0,0.0,0.0,0.0,1.0
77054,Muscovy Mix,White/Green,2018-01-05T13:23:00,Partner,Transfer,Unknown,365,1.0,0.0,0.0,0.0,1.0
77868,Chicken Mix,Tan/Red,2018-01-24T14:32:00,NaN,Adoption,Intact Male,180,1.0,0.0,0.0,0.0,1.0
78118,Chicken Mix,Black/White,2018-01-29T19:42:00,Foster,Adoption,Intact Female,365,1.0,0.0,0.0,0.0,1.0
78206,Pheasant Mix,Gold/Brown,2018-01-18T15:49:00,Partner,Transfer,Unknown,730,1.0,0.0,0.0,0.0,1.0

In [34]:
data['Other'] += data['Livestock']
data[data['Livestock'] == 1]

,breed,color,datetime,outcome_subtype,outcome_type,sex_upon_outcome,age_days,Bird,Cat,Dog,Livestock,Other
2240,Pig Mix,Black/White,2013-11-30T12:18:00,NaN,Return to Owner,Intact Female,180,0.0,0.0,0.0,1.0,1.0
11609,Goat Mix,Black,2014-06-17T10:30:00,Partner,Transfer,Intact Male,180,0.0,0.0,0.0,1.0,1.0
17291,Miniature,Liver/Cream,2013-10-03T10:59:00,Partner,Transfer,Intact Male,1825,0.0,0.0,0.0,1.0,1.0
19396,Pig Mix,Black/White,2014-03-11T14:39:00,Foster,Adoption,Neutered Male,365,0.0,0.0,0.0,1.0,1.0
22609,Pig Mix,Black,2014-03-29T14:00:00,Foster,Adoption,Unknown,35,0.0,0.0,0.0,1.0,1.0
31005,Pig Mix,Pink,2015-05-11T00:00:00,Partner,Transfer,Intact Female,730,0.0,0.0,0.0,1.0,1.0
42901,Goat Mix,Brown,2015-12-07T00:00:00,Partner,Transfer,Unknown,365,0.0,0.0,0.0,1.0,1.0
43388,Potbelly Pig Mix,Black/White,2017-03-15T12:49:00,Partner,Transfer,Intact Female,210,0.0,0.0,0.0,1.0,1.0
60692,Pig Mix,White,2016-01-27T00:00:00,Partner,Transfer,Intact Male,365,0.0,0.0,0.0,1.0,1.0

In [35]:
data.drop(['Bird', 'Livestock'], axis = 1, inplace = True)
data

,breed,color,datetime,outcome_subtype,outcome_type,sex_upon_outcome,age_days,Cat,Dog,Other
0,Domestic Shorthair Mix,Orange Tabby,2014-07-22T16:04:00,Partner,Transfer,Intact Male,14,1.0,0.0,0.0
1,Beagle Mix,White/Brown,2013-11-07T11:47:00,Partner,Transfer,Spayed Female,365,0.0,1.0,0.0
2,Pit Bull,Blue/White,2014-06-03T14:20:00,NaN,Adoption,Neutered Male,365,0.0,1.0,0.0
3,Miniature Schnauzer Mix,White,2014-06-15T15:50:00,Partner,Transfer,Neutered Male,3285,0.0,1.0,0.0
4,Bat Mix,Brown,2014-07-07T14:04:00,Rabies Risk,Euthanasia,Unknown,150,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...
78250,Golden Retriever/Labrador Retriever,Brown/White,2018-02-01T18:40:00,Foster,Adoption,Neutered Male,30,0.0,1.0,0.0
78251,Golden Retriever/Labrador Retriever,Brown/White,2018-02-01T18:26:00,Foster,Adoption,Spayed Female,30,0.0,1.0,0.0
78252,Mastiff Mix,Blue/White,2018-02-01T18:06:00,NaN,Adoption,Neutered Male,1095,0.0,1.0,0.0
78254,Standard Schnauzer,Red,2018-02-01T18:32:00,NaN,Adoption,Spayed Female,60,0.0,1.0,0.0
78255,Labrador Retriever Mix,White/Brown,2018-02-01T18:44:00,NaN,Adoption,Neutered Male,60,0.0,1.0,0.0

In [36]:
sex_upon_outcome = data['sex_upon_outcome'].get_values().reshape(-1, 1)

# One-hot encoding
oh_encoder = preprocessing.OneHotEncoder()
oh_encoder.fit(sex_upon_outcome)
oh_result = oh_encoder.transform(sex_upon_outcome).toarray()

/Users/user/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: FutureWarning: The 'get_values' method is deprecated and will be removed in a future version. Use '.to_numpy()' or '.array' instead.
  """Entry point for launching an IPython kernel.

In [37]:
name = ['Intact Female','Intact Male', 'Neutered Male','Spayed Female','Unknown' ]
# data.drop(name, axis=1, inplace = True)

In [38]:
tmp = pd.DataFrame(oh_result, columns=name)
tmp.index = data.index

In [39]:
data = pd.concat([data, tmp], axis=1)
data.drop(['sex_upon_outcome'], axis=1, inplace = True)

In [40]:
data

,breed,color,datetime,outcome_subtype,outcome_type,age_days,Cat,Dog,Other,Intact Female,Intact Male,Neutered Male,Spayed Female,Unknown
0,Domestic Shorthair Mix,Orange Tabby,2014-07-22T16:04:00,Partner,Transfer,14,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
1,Beagle Mix,White/Brown,2013-11-07T11:47:00,Partner,Transfer,365,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
2,Pit Bull,Blue/White,2014-06-03T14:20:00,NaN,Adoption,365,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0
3,Miniature Schnauzer Mix,White,2014-06-15T15:50:00,Partner,Transfer,3285,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0
4,Bat Mix,Brown,2014-07-07T14:04:00,Rabies Risk,Euthanasia,150,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
78250,Golden Retriever/Labrador Retriever,Brown/White,2018-02-01T18:40:00,Foster,Adoption,30,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0
78251,Golden Retriever/Labrador Retriever,Brown/White,2018-02-01T18:26:00,Foster,Adoption,30,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
78252,Mastiff Mix,Blue/White,2018-02-01T18:06:00,NaN,Adoption,1095,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0
78254,Standard Schnauzer,Red,2018-02-01T18:32:00,NaN,Adoption,60,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
78255,Labrador Retriever Mix,White/Brown,2018-02-01T18:44:00,NaN,Adoption,60,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0

In [41]:
profile = ProfileReport(data)
profile

/Users/user/anaconda3/lib/python3.7/site-packages/pandas_profiling/describe.py:392: FutureWarning: The join_axes-keyword is deprecated. Use .reindex or .reindex_like on the result to achieve the same functionality.
  variable_stats = pd.concat(ldesc, join_axes=pd.Index([names]), axis=1)

In [42]:
data['outcome_subtype'].unique()

array(['Partner', nan, 'Rabies Risk', 'Suffering', 'Offsite', 'Foster',
       'SCRP', 'In Kennel', 'Aggressive', 'Medical', 'Behavior', 'At Vet',
       'In Foster', 'Enroute', 'In Surgery', 'Possible Theft',
       'Court/Investigation', 'Barn', 'Snr', 'Underage'], dtype=object)

In [43]:
data[data['outcome_subtype']=='Barn']

,breed,color,datetime,outcome_subtype,outcome_type,age_days,Cat,Dog,Other,Intact Female,Intact Male,Neutered Male,Spayed Female,Unknown
21732,Domestic Shorthair Mix,Blue Tabby,2014-09-15T13:24:00,Barn,Adoption,1460,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
26617,Domestic Shorthair Mix,Black,2015-01-26T14:55:00,Barn,Transfer,1095,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
70147,Dachshund Mix,Tan/Black,2017-03-13T16:21:00,Barn,Transfer,1095,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0

In [44]:
data[data['outcome_subtype']=='Partner']

,breed,color,datetime,outcome_subtype,outcome_type,age_days,Cat,Dog,Other,Intact Female,Intact Male,Neutered Male,Spayed Female,Unknown
0,Domestic Shorthair Mix,Orange Tabby,2014-07-22T16:04:00,Partner,Transfer,14,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
1,Beagle Mix,White/Brown,2013-11-07T11:47:00,Partner,Transfer,365,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
3,Miniature Schnauzer Mix,White,2014-06-15T15:50:00,Partner,Transfer,3285,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0
5,Leonberger Mix,Brown/White,2013-10-07T13:06:00,Partner,Transfer,120,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0
7,Chihuahua Shorthair Mix,Brown,2014-12-08T15:55:00,Partner,Transfer,1095,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
78207,American Bulldog Mix,Brown Brindle/White,2018-02-01T00:00:00,Partner,Transfer,1460,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0
78211,West Highland Mix,White,2018-01-31T11:51:00,Partner,Transfer,2920,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0
78214,Cardigan Welsh Corgi/Miniature Schnauzer,Gray/Tan,2018-01-31T11:51:00,Partner,Transfer,730,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
78233,Domestic Shorthair Mix,Brown Tabby,2018-02-01T17:51:00,Partner,Transfer,365,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
78234,Cocker Spaniel Mix,Cream,2018-02-01T16:34:00,Partner,Transfer,2555,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0

bad
 'In Surgery', 
    'In Foster',
    'Court/Investigation',
    'Behavior',
    'Medical',
    'Aggressive',
    'Suffering',
    'Rabies Risk',
    'Underage',
    'Enroute',
    'In Kennel',
    'At Vet',
    'Possible Theft',
    'Barn'

good
    'Foster',
    'Snr',
    'SCRP',
    'Offsite',
    'Partner'

In [45]:
data.drop(['datetime', 'breed', 'color'], axis = 1, inplace = True)

data.head()

,outcome_subtype,outcome_type,age_days,Cat,Dog,Other,Intact Female,Intact Male,Neutered Male,Spayed Female,Unknown
0,Partner,Transfer,14,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
1,Partner,Transfer,365,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
2,NaN,Adoption,365,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0
3,Partner,Transfer,3285,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0
4,Rabies Risk,Euthanasia,150,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0

In [46]:
good_marker = ['Foster', 'Snr', 'SCRP', 'Offsite', 'Partner']
bad_marker = ['In Surgery', 'In Foster', 'Court/Investigation', 
              'Behavior', 'Medical', 'Aggressive', 'Suffering', 
              'Rabies Risk', 'Underage', 'Enroute', 'In Kennel', 
              'At Vet' , 'Possible Theft', 'Barn']

In [49]:
data['marker'] = data['outcome_subtype']\
    .map({'Foster':'Foster', 'Snr': 'Snr','SCRP':'SCRP', 'Offsite': 'Offsite', 'Partner':'Partner'})\
    .fillna('bad_marker')

In [48]:
# data['marker'] = ''

# for i in data.index:
#     t = data['outcome_subtype'][i]
#     if t in good_marker:
#         data['marker'][i] = data['outcome_subtype'][i]
#     else:
#         data['marker'][i] = 'bad_marker'

In [50]:
data.drop(['outcome_subtype'], axis=1, inplace=True)
data.head()

,outcome_type,age_days,Cat,Dog,Other,Intact Female,Intact Male,Neutered Male,Spayed Female,Unknown,marker
0,Transfer,14,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,Partner
1,Transfer,365,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,Partner
2,Adoption,365,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,bad_marker
3,Transfer,3285,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,Partner
4,Euthanasia,150,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,bad_marker

In [51]:
marker = data['marker'].get_values().reshape(-1, 1)

# One-hot encoding
oh_encoder = preprocessing.OneHotEncoder()
oh_encoder.fit(marker)
oh_result = oh_encoder.transform(marker).toarray()

oh_result

/Users/user/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: FutureWarning: The 'get_values' method is deprecated and will be removed in a future version. Use '.to_numpy()' or '.array' instead.
  """Entry point for launching an IPython kernel.

array([[0., 0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1.],
       ...,
       [0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 1.]])

In [52]:
name = ['Foster','Offsite', 'Partner','SCRP','Snr','bad_marker' ]

In [53]:
tmp = pd.DataFrame(oh_result, columns=name)
tmp.index = data.index

In [54]:
data = pd.concat([data, tmp], axis=1)

In [56]:
data.drop(['marker'], axis=1, inplace = True)
data.drop(['Other','Unknown'], axis=1, inplace = True)

In [609]:
# data.drop(name,axis=1,inplace = True)

In [57]:
data

,outcome_type,age_days,Cat,Dog,Intact Female,Intact Male,Neutered Male,Spayed Female,Foster,Offsite,Partner,SCRP,Snr,bad_marker
0,Transfer,14,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
1,Transfer,365,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0
2,Adoption,365,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
3,Transfer,3285,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
4,Euthanasia,150,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
78250,Adoption,30,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
78251,Adoption,30,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0
78252,Adoption,1095,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
78254,Adoption,60,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0
78255,Adoption,60,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0

In [58]:
profile = ProfileReport(data)
profile

/Users/user/anaconda3/lib/python3.7/site-packages/pandas_profiling/describe.py:392: FutureWarning: The join_axes-keyword is deprecated. Use .reindex or .reindex_like on the result to achieve the same functionality.
  variable_stats = pd.concat(ldesc, join_axes=pd.Index([names]), axis=1)

In [59]:
data.drop('Dog',axis=1, inplace=True)

In [60]:
data

,outcome_type,age_days,Cat,Intact Female,Intact Male,Neutered Male,Spayed Female,Foster,Offsite,Partner,SCRP,Snr,bad_marker
0,Transfer,14,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
1,Transfer,365,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0
2,Adoption,365,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
3,Transfer,3285,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
4,Euthanasia,150,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
78250,Adoption,30,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
78251,Adoption,30,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0
78252,Adoption,1095,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
78254,Adoption,60,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0
78255,Adoption,60,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0

In [61]:
data.outcome_type.unique()

array(['Transfer', 'Adoption', 'Euthanasia', 'Return to Owner', 'Died',
       'Disposal', 'Relocate', 'Missing', 'Rto-Adopt'], dtype=object)

In [63]:
data['outcome_type'] = data['outcome_type']\
    .map({'Transfer':'Transfer', 'Adoption': 'Adoption'})\
    .fillna('other')
data.head()

,outcome_type,age_days,Cat,Intact Female,Intact Male,Neutered Male,Spayed Female,Foster,Offsite,Partner,SCRP,Snr,bad_marker
0,Transfer,14,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
1,Transfer,365,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0
2,Adoption,365,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
3,Transfer,3285,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
4,other,150,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0

In [64]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.datasets import make_classification

In [65]:
from sklearn.model_selection import train_test_split

In [66]:
X = data[data.columns.difference(['outcome_type'])] 
y  = data['outcome_type']

In [67]:
le = preprocessing.LabelEncoder()
le.fit(y)

y = le.transform(data['outcome_type'])

In [68]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=30)

In [69]:
X_train.head()

,Cat,Foster,Intact Female,Intact Male,Neutered Male,Offsite,Partner,SCRP,Snr,Spayed Female,age_days,bad_marker
62620,1.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,90,0.0
10861,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,90,0.0
77410,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1460,1.0
16072,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,365,0.0
48844,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,120,1.0

In [70]:
X_test.head()

,Cat,Foster,Intact Female,Intact Male,Neutered Male,Offsite,Partner,SCRP,Snr,Spayed Female,age_days,bad_marker
52908,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,5110,1.0
30792,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,2920,0.0
35913,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,30,0.0
10207,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,3285,1.0
64468,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1095,1.0

In [72]:
y_train

array([0, 1, 0, ..., 1, 2, 1])

In [73]:
y_test

array([2, 0, 0, ..., 1, 2, 0])

In [74]:
clf = RandomForestClassifier(random_state=0)
clf.fit(X_train, y_train)

y_pred = clf.predict(X_test)

/Users/user/anaconda3/lib/python3.7/site-packages/sklearn/ensemble/forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)

In [75]:
from sklearn.metrics import mean_squared_error
from sklearn.metrics import confusion_matrix, accuracy_score


print(mean_squared_error(y_test, y_pred)**0.5)
print(confusion_matrix(y_test, y_pred))
print(accuracy_score(y_test, y_pred))

0.7519572280400235
[[5673    0  901]
 [   0 4762    0]
 [1311    0 3001]]
0.858640081799591

In [76]:
pd.Series(y_test).value_counts()

0    6574
1    4762
2    4312
dtype: int64